import { KeyboardLayout } from "@/features/spec/keyboardLayoutSchema";

export const US_QWERTY_FULL_LAYOUT: KeyboardLayout = {
  name: "US QWERTY Full-Size",
  description:
    "Full-size US QWERTY layout with F-keys, navigation cluster, and numpad",
  rows: [
    // F-key row
    [
      { id: "esc", label: "Esc" },
      { id: null, label: "", widthScale: 1 },
      { id: "f1", label: "F1" },
      { id: "f2", label: "F2" },
      { id: "f3", label: "F3" },
      { id: "f4", label: "F4" },
      { id: null, label: "", widthScale: 0.5 },
      { id: "f5", label: "F5" },
      { id: "f6", label: "F6" },
      { id: "f7", label: "F7" },
      { id: "f8", label: "F8" },
      { id: null, label: "", widthScale: 0.5 },
      { id: "f9", label: "F9" },
      { id: "f10", label: "F10" },
      { id: "f11", label: "F11" },
      { id: "f12", label: "F12" },
      { id: null, label: "", widthScale: 0.25 },
      { id: "print", label: "PrtSc" },
      { id: "scroll", label: "ScrLk" },
      { id: "pause", label: "Pause" },
    ],
    // Number row
    [
      { id: "grave", label: "`" },
      { id: "1", label: "1" },
      { id: "2", label: "2" },
      { id: "3", label: "3" },
      { id: "4", label: "4" },
      { id: "5", label: "5" },
      { id: "6", label: "6" },
      { id: "7", label: "7" },
      { id: "8", label: "8" },
      { id: "9", label: "9" },
      { id: "0", label: "0" },
      { id: "minus", label: "-" },
      { id: "equals", label: "=" },
      { id: "backspace", label: "Backspace", widthScale: 2 },
      { id: null, label: "", widthScale: 0.25 },
      { id: "insert", label: "Ins" },
      { id: "home", label: "Home" },
      { id: "page-up", label: "PgUp" },
      { id: null, label: "", widthScale: 0.25 },
      { id: "numlock", label: "Num" },
      { id: "num-slash", label: "/" },
      { id: "num-asterisk", label: "*" },
      { id: "num-minus", label: "-" },
    ],
    // QWERTY row
    [
      { id: "tab", label: "Tab", widthScale: 1.5 },
      { id: "q", label: "Q" },
      { id: "w", label: "W" },
      { id: "e", label: "E" },
      { id: "r", label: "R" },
      { id: "t", label: "T" },
      { id: "y", label: "Y" },
      { id: "u", label: "U" },
      { id: "i", label: "I" },
      { id: "o", label: "O" },
      { id: "p", label: "P" },
      { id: "bracket-left", label: "[" },
      { id: "bracket-right", label: "]" },
      { id: "backslash", label: "\\", widthScale: 1.5 },
      { id: null, label: "", widthScale: 0.25 },
      { id: "delete", label: "Del" },
      { id: "end", label: "End" },
      { id: "page-down", label: "PgDn" },
      { id: null, label: "", widthScale: 0.25 },
      { id: "num-7", label: "7" },
      { id: "num-8", label: "8" },
      { id: "num-9", label: "9" },
      { id: "num-plus", label: "+" },
    ],
    // ASDF row
    [
      { id: "caps", label: "Caps", widthScale: 1.75 },
      { id: "a", label: "A" },
      { id: "s", label: "S" },
      { id: "d", label: "D" },
      { id: "f", label: "F" },
      { id: "g", label: "G" },
      { id: "h", label: "H" },
      { id: "j", label: "J" },
      { id: "k", label: "K" },
      { id: "l", label: "L" },
      { id: "semicolon", label: ";" },
      { id: "quote", label: "'" },
      { id: "enter", label: "Enter", widthScale: 2.25 },
      { id: null, label: "", widthScale: 3.5 },
      { id: "num-4", label: "4" },
      { id: "num-5", label: "5" },
      { id: "num-6", label: "6" },
      { id: null, label: "", widthScale: 1 },
    ],
    // ZXCV row
    [
      { id: "shift-left", label: "Shift", widthScale: 2.25 },
      { id: "z", label: "Z" },
      { id: "x", label: "X" },
      { id: "c", label: "C" },
      { id: "v", label: "V" },
      { id: "b", label: "B" },
      { id: "n", label: "N" },
      { id: "m", label: "M" },
      { id: "comma", label: "," },
      { id: "period", label: "." },
      { id: "slash", label: "/" },
      { id: "shift-right", label: "Shift", widthScale: 2.75 },
      { id: null, label: "", widthScale: 1.25 },
      { id: "arrow-up", label: "↑" },
      { id: null, label: "", widthScale: 1.25 },
      { id: "num-1", label: "1" },
      { id: "num-2", label: "2" },
      { id: "num-3", label: "3" },
      { id: "num-enter", label: "Enter" },
    ],
    // Bottom row
    [
      { id: "ctrl-left", label: "Ctrl", widthScale: 1.25 },
      { id: "meta-left", label: "Win", widthScale: 1.25 },
      { id: "alt-left", label: "Alt", widthScale: 1.25 },
      { id: "space", label: "Space", widthScale: 6.25 },
      { id: "alt-right", label: "Alt", widthScale: 1.25 },
      { id: "fn", label: "Fn", widthScale: 1.25 },
      { id: "menu", label: "Menu", widthScale: 1.25 },
      { id: "ctrl-right", label: "Ctrl", widthScale: 1.25 },
      { id: null, label: "", widthScale: 0.25 },
      { id: "arrow-left", label: "←" },
      { id: "arrow-down", label: "↓" },
      { id: "arrow-right", label: "→" },
      { id: null, label: "", widthScale: 0.25 },
      { id: "num-0", label: "0", widthScale: 2 },
      { id: "num-period", label: "." },
      { id: null, label: "", widthScale: 1 },
    ],
  ],
};
